export *  from './../app/app.component';
export * from './home/home';
export * from './slide/slide';
export * from './sugn/sugn';
export * from './registr/registr';
export * from './reg-code/reg-code';
export * from './code-mail/code-mail';
export * from './code-telphone/code-telphone';
export * from './menu/menu';
export * from './edit/edit';
export * from './photo/photo';
export * from './order/order';
export * from './other-header';
export * from './frame/frame'